### ISSUE TITLE
Problema en charge 4

### ISSUE THREAD

**Issue by mrblasterdj** [pembem22/jbl-firmware#1]
Buenas tardes! baje la app ConnectPlus, conecte jbl charge 4 por bluetooth al dispositivo, pero no me aparece que chipset tiene, hay alguna otra forma de saberlo? para saber que firmware descargar, muchas gracias, saludos.

**Comment by mrblasterdj** [comment]
desde la app, solo me aparece el modelo, color, scan record bytes y mac address

**Comment by mrblasterdj** [comment]
Lo otro que iba a consultar, es si se consigue la versión 2.7.0, esa versión venia en mi charge 4, desde que se actualizo a la 3.0.0 tengo muchos problemas con el bluetooth, se entre cortan las canciones, y también me pasa que tengo que dejarlo 10 min prendido mínimo, para poder conectar un dispositivo, sino no conecta a ninguno

**Comment by pembem22** [comment]
Hello, you are correct. The 1.1.3 version of ConnectPlus doesn't show chipset information, this functionality was added after that release. I'll upload a new build of ConnectPlus later.

Unfortunately, I don't have 2.7.0 firmware file. There are earlier versions available, but they are marked as for testing and I wouldn't recommend them.

Also, please use English for discussion if possible.

**Comment by mrblasterdj** [comment]
OK thank you very much! I wait for you to upload the new ConnectPlus apk, greetings!

**Comment by mrblasterdj** [comment]
Hello, I wanted to know if you will upload the new version of the connectplus app

**Comment by pembem22** [comment]
Hi, it's not stable enough yet. I will upload it when it's ready, but that may take some time.

**Comment by mrblasterdj** [comment]
It doesn't matter if it's not stable, I just need to know what chip it has, then I uninstall it and install version 1.1.3 to update the firmware. thank you very much, greetings

**Comment by pembem22** [comment]
I've uploaded a new build of ConnectPlus, so I'm closing this issue. If you have any problems or requests regarding the app in the future, please, create an issue in the corresponding repository.
