### ISSUE TITLE
Can't install DFU How to install .bin??? Xtreme 2 GT

### ISSUE THREAD

**Issue by AuztiinAnonX** [pembem22/jbl-firmware#3]
I have an Xtreme 2 GT that came with 2.7.0 and I'm trying to install the .bin firmware files but ConnectPlus only accepts .dfu and those dfu files didn't work and resulted in an error. I tried placing 8.8.8 bin file on USB flash drive plugging it into the JBL Xtreme 2's USB port though I don't know how to start the update. Certain button combination? Can't enter DFU has error and just reboots into normal mode. I have tried previous ConnectPlus but updated to 1.2 pre release with same errors

**Comment by AuztiinAnonX** [comment]
Downgraded ConnectPlus version and was able to start flash for Xtreme 2 QCC .bin but resulted in an error after 100% on different .bin's

**Comment by AuztiinAnonX** [comment]
Guess all of the QCC .bin's failed after 100% but if you can get your hands on a newer QCC v8.8.8 Xtreme 2 firmware I could be in heaven and may even donate a few cups of coffee for helping me fix my missing Low Frequency Mode problem

**Comment by AuztiinAnonX** [comment]
Also unable to connect to storage.harman.com I get this:
Status:	Resolving address of storage.harman.com
Status:	Connecting to 204.109.57.186:21...
Status:	Connection attempt failed with "ECONNREFUSED - Connection refused by server".
Error:	Could not connect to server
Status:	Disconnected from server
Status:	Resolving address of storage.harman.com
Status:	Connecting to 204.109.57.186:8080...
Status:	Connection established, waiting for welcome message...
Error:	Connection closed by server
Error:	Could not connect to server

**Comment by pembem22** [comment]
Hi, there's no support for flashing QCC firmware files in the app.

Please check the relevant issue [here](https://github.com/pembem22/connect-plus/issues/58). This repository is for firmware files.
