### ISSUE TITLE
request for fw HARMAN kardon

### ISSUE THREAD

**Issue by majidmp97** [pembem22/jbl-firmware#4]
**hi request dont work use Issues tab
i have HARMAN KARDON GO + PLAY it have exact Bluetooth module like jbl-charge_3
and the module loos the firmware somehow
can you make hardware way firmware for it
i contact the  HARMAN KARDON co the don't give use anything
the just say i need to replace mainboard**

**Comment by pembem22** [comment]
Hi, there doesn't seem to be any firmware available for the Go+Play model, as it is not supported by any app.
