### ISSUE TITLE
JBL XTREME 2 QCC GM ERROR

### ISSUE THREAD

**Issue by SotirisSerJohn** [pembem22/jbl-firmware#5]
The only file is 8.8.8 and its not a .dfu file. I tried flashing XTREME 2 cgq or smthng but nothing. I also tried renamein the original file but still nothing. Any help? I really want lfm

**Comment by pembem22** [comment]
Please only create issues in relevant repositories. What you probably want is [flashing *.bin firmware for qcc versions](https://github.com/pembem22/connect-plus/issues/58).
