### ISSUE TITLE
Jbl Xtreme 2 QCC Flash

### ISSUE THREAD

**Issue by JavaScriptChri** [pembem22/jbl-firmware#8]
How can I flash the jbl xtreme 2 QCC software? I downloaded ConnectPlus and the files in the folder but i can't flash it because it's not a .dfu file.

**Comment by pembem22** [comment]
Hi, there's no support for flashing QCC firmware files in the app.

Please check the relevant issue https://github.com/pembem22/connect-plus/issues/58. This repository is for firmware files.
